server:
  port: 8088
spring:
  application:
    name: shopping-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yanjj0218/springshopping.git
          username:
          password:
          search-paths: serverconfig/*
  rabbitmq:
    host: 192.168.134.128
    port: 5672
    username: yan
    password: 123456
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
