server:
  port: 8089
spring:
  application:
    name: shoppingconsumer
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 10Mb